# Autogenerated wrapper script for avrdude_jll for i686-linux-gnu
export avrdude

using libusb_jll
JLLWrappers.@generate_wrapper_header("avrdude")
JLLWrappers.@declare_executable_product(avrdude)
function __init__()
    JLLWrappers.@generate_init_header(libusb_jll)
    JLLWrappers.@init_executable_product(
        avrdude,
        "bin/avrdude",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
